package com.yang.ccks2.model;

import java.io.Serializable;

public class CcksText implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ccks_text.text_id
     *
     * @mbg.generated Sun Dec 27 14:50:31 CST 2020
     */
    private Long textId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ccks_text.text_name
     *
     * @mbg.generated Sun Dec 27 14:50:31 CST 2020
     */
    private String textName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ccks_text.text_content
     *
     * @mbg.generated Sun Dec 27 14:50:31 CST 2020
     */
    private String textContent;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table ccks_text
     *
     * @mbg.generated Sun Dec 27 14:50:31 CST 2020
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ccks_text.text_id
     *
     * @return the value of ccks_text.text_id
     *
     * @mbg.generated Sun Dec 27 14:50:31 CST 2020
     */
    public Long getTextId() {
        return textId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ccks_text.text_id
     *
     * @param textId the value for ccks_text.text_id
     *
     * @mbg.generated Sun Dec 27 14:50:31 CST 2020
     */
    public void setTextId(Long textId) {
        this.textId = textId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ccks_text.text_name
     *
     * @return the value of ccks_text.text_name
     *
     * @mbg.generated Sun Dec 27 14:50:31 CST 2020
     */
    public String getTextName() {
        return textName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ccks_text.text_name
     *
     * @param textName the value for ccks_text.text_name
     *
     * @mbg.generated Sun Dec 27 14:50:31 CST 2020
     */
    public void setTextName(String textName) {
        this.textName = textName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ccks_text.text_content
     *
     * @return the value of ccks_text.text_content
     *
     * @mbg.generated Sun Dec 27 14:50:31 CST 2020
     */
    public String getTextContent() {
        return textContent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ccks_text.text_content
     *
     * @param textContent the value for ccks_text.text_content
     *
     * @mbg.generated Sun Dec 27 14:50:31 CST 2020
     */
    public void setTextContent(String textContent) {
        this.textContent = textContent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ccks_text
     *
     * @mbg.generated Sun Dec 27 14:50:31 CST 2020
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", textId=").append(textId);
        sb.append(", textName=").append(textName);
        sb.append(", textContent=").append(textContent);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}