package com.yang.ccks2.model;

import java.io.Serializable;

public class CcksUser implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ccks_user.user_id
     *
     * @mbg.generated Sun Dec 27 14:50:31 CST 2020
     */
    private Long userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ccks_user.user_name
     *
     * @mbg.generated Sun Dec 27 14:50:31 CST 2020
     */
    private String userName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table ccks_user
     *
     * @mbg.generated Sun Dec 27 14:50:31 CST 2020
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ccks_user.user_id
     *
     * @return the value of ccks_user.user_id
     *
     * @mbg.generated Sun Dec 27 14:50:31 CST 2020
     */
    public Long getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ccks_user.user_id
     *
     * @param userId the value for ccks_user.user_id
     *
     * @mbg.generated Sun Dec 27 14:50:31 CST 2020
     */
    public void setUserId(Long userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ccks_user.user_name
     *
     * @return the value of ccks_user.user_name
     *
     * @mbg.generated Sun Dec 27 14:50:31 CST 2020
     */
    public String getUserName() {
        return userName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ccks_user.user_name
     *
     * @param userName the value for ccks_user.user_name
     *
     * @mbg.generated Sun Dec 27 14:50:31 CST 2020
     */
    public void setUserName(String userName) {
        this.userName = userName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ccks_user
     *
     * @mbg.generated Sun Dec 27 14:50:31 CST 2020
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", userId=").append(userId);
        sb.append(", userName=").append(userName);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}