package com.yang.ccks2.model;

import java.util.ArrayList;
import java.util.List;

public class CcksTextExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table ccks_text
     *
     * @mbg.generated Sun Dec 27 14:50:31 CST 2020
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table ccks_text
     *
     * @mbg.generated Sun Dec 27 14:50:31 CST 2020
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table ccks_text
     *
     * @mbg.generated Sun Dec 27 14:50:31 CST 2020
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ccks_text
     *
     * @mbg.generated Sun Dec 27 14:50:31 CST 2020
     */
    public CcksTextExample() {
        oredCriteria = new ArrayList<>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ccks_text
     *
     * @mbg.generated Sun Dec 27 14:50:31 CST 2020
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ccks_text
     *
     * @mbg.generated Sun Dec 27 14:50:31 CST 2020
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ccks_text
     *
     * @mbg.generated Sun Dec 27 14:50:31 CST 2020
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ccks_text
     *
     * @mbg.generated Sun Dec 27 14:50:31 CST 2020
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ccks_text
     *
     * @mbg.generated Sun Dec 27 14:50:31 CST 2020
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ccks_text
     *
     * @mbg.generated Sun Dec 27 14:50:31 CST 2020
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ccks_text
     *
     * @mbg.generated Sun Dec 27 14:50:31 CST 2020
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ccks_text
     *
     * @mbg.generated Sun Dec 27 14:50:31 CST 2020
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ccks_text
     *
     * @mbg.generated Sun Dec 27 14:50:31 CST 2020
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ccks_text
     *
     * @mbg.generated Sun Dec 27 14:50:31 CST 2020
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table ccks_text
     *
     * @mbg.generated Sun Dec 27 14:50:31 CST 2020
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andTextIdIsNull() {
            addCriterion("text_id is null");
            return (Criteria) this;
        }

        public Criteria andTextIdIsNotNull() {
            addCriterion("text_id is not null");
            return (Criteria) this;
        }

        public Criteria andTextIdEqualTo(Long value) {
            addCriterion("text_id =", value, "textId");
            return (Criteria) this;
        }

        public Criteria andTextIdNotEqualTo(Long value) {
            addCriterion("text_id <>", value, "textId");
            return (Criteria) this;
        }

        public Criteria andTextIdGreaterThan(Long value) {
            addCriterion("text_id >", value, "textId");
            return (Criteria) this;
        }

        public Criteria andTextIdGreaterThanOrEqualTo(Long value) {
            addCriterion("text_id >=", value, "textId");
            return (Criteria) this;
        }

        public Criteria andTextIdLessThan(Long value) {
            addCriterion("text_id <", value, "textId");
            return (Criteria) this;
        }

        public Criteria andTextIdLessThanOrEqualTo(Long value) {
            addCriterion("text_id <=", value, "textId");
            return (Criteria) this;
        }

        public Criteria andTextIdIn(List<Long> values) {
            addCriterion("text_id in", values, "textId");
            return (Criteria) this;
        }

        public Criteria andTextIdNotIn(List<Long> values) {
            addCriterion("text_id not in", values, "textId");
            return (Criteria) this;
        }

        public Criteria andTextIdBetween(Long value1, Long value2) {
            addCriterion("text_id between", value1, value2, "textId");
            return (Criteria) this;
        }

        public Criteria andTextIdNotBetween(Long value1, Long value2) {
            addCriterion("text_id not between", value1, value2, "textId");
            return (Criteria) this;
        }

        public Criteria andTextNameIsNull() {
            addCriterion("text_name is null");
            return (Criteria) this;
        }

        public Criteria andTextNameIsNotNull() {
            addCriterion("text_name is not null");
            return (Criteria) this;
        }

        public Criteria andTextNameEqualTo(String value) {
            addCriterion("text_name =", value, "textName");
            return (Criteria) this;
        }

        public Criteria andTextNameNotEqualTo(String value) {
            addCriterion("text_name <>", value, "textName");
            return (Criteria) this;
        }

        public Criteria andTextNameGreaterThan(String value) {
            addCriterion("text_name >", value, "textName");
            return (Criteria) this;
        }

        public Criteria andTextNameGreaterThanOrEqualTo(String value) {
            addCriterion("text_name >=", value, "textName");
            return (Criteria) this;
        }

        public Criteria andTextNameLessThan(String value) {
            addCriterion("text_name <", value, "textName");
            return (Criteria) this;
        }

        public Criteria andTextNameLessThanOrEqualTo(String value) {
            addCriterion("text_name <=", value, "textName");
            return (Criteria) this;
        }

        public Criteria andTextNameLike(String value) {
            addCriterion("text_name like", value, "textName");
            return (Criteria) this;
        }

        public Criteria andTextNameNotLike(String value) {
            addCriterion("text_name not like", value, "textName");
            return (Criteria) this;
        }

        public Criteria andTextNameIn(List<String> values) {
            addCriterion("text_name in", values, "textName");
            return (Criteria) this;
        }

        public Criteria andTextNameNotIn(List<String> values) {
            addCriterion("text_name not in", values, "textName");
            return (Criteria) this;
        }

        public Criteria andTextNameBetween(String value1, String value2) {
            addCriterion("text_name between", value1, value2, "textName");
            return (Criteria) this;
        }

        public Criteria andTextNameNotBetween(String value1, String value2) {
            addCriterion("text_name not between", value1, value2, "textName");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table ccks_text
     *
     * @mbg.generated do_not_delete_during_merge Sun Dec 27 14:50:31 CST 2020
     */
    public static class Criteria extends GeneratedCriteria {
        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table ccks_text
     *
     * @mbg.generated Sun Dec 27 14:50:31 CST 2020
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}