package com.yang.ccks2.model;

import java.io.Serializable;

public class CcksEntity implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ccks_entity.entity_id
     *
     * @mbg.generated Sun Dec 27 14:50:31 CST 2020
     */
    private Long entityId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ccks_entity.entity_content
     *
     * @mbg.generated Sun Dec 27 14:50:31 CST 2020
     */
    private String entityContent;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ccks_entity.start_index
     *
     * @mbg.generated Sun Dec 27 14:50:31 CST 2020
     */
    private Integer startIndex;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ccks_entity.end_index
     *
     * @mbg.generated Sun Dec 27 14:50:31 CST 2020
     */
    private Integer endIndex;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ccks_entity.text_id
     *
     * @mbg.generated Sun Dec 27 14:50:31 CST 2020
     */
    private Long textId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ccks_entity.commit_user_id
     *
     * @mbg.generated Sun Dec 27 14:50:31 CST 2020
     */
    private Long commitUserId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table ccks_entity
     *
     * @mbg.generated Sun Dec 27 14:50:31 CST 2020
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ccks_entity.entity_id
     *
     * @return the value of ccks_entity.entity_id
     *
     * @mbg.generated Sun Dec 27 14:50:31 CST 2020
     */
    public Long getEntityId() {
        return entityId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ccks_entity.entity_id
     *
     * @param entityId the value for ccks_entity.entity_id
     *
     * @mbg.generated Sun Dec 27 14:50:31 CST 2020
     */
    public void setEntityId(Long entityId) {
        this.entityId = entityId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ccks_entity.entity_content
     *
     * @return the value of ccks_entity.entity_content
     *
     * @mbg.generated Sun Dec 27 14:50:31 CST 2020
     */
    public String getEntityContent() {
        return entityContent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ccks_entity.entity_content
     *
     * @param entityContent the value for ccks_entity.entity_content
     *
     * @mbg.generated Sun Dec 27 14:50:31 CST 2020
     */
    public void setEntityContent(String entityContent) {
        this.entityContent = entityContent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ccks_entity.start_index
     *
     * @return the value of ccks_entity.start_index
     *
     * @mbg.generated Sun Dec 27 14:50:31 CST 2020
     */
    public Integer getStartIndex() {
        return startIndex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ccks_entity.start_index
     *
     * @param startIndex the value for ccks_entity.start_index
     *
     * @mbg.generated Sun Dec 27 14:50:31 CST 2020
     */
    public void setStartIndex(Integer startIndex) {
        this.startIndex = startIndex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ccks_entity.end_index
     *
     * @return the value of ccks_entity.end_index
     *
     * @mbg.generated Sun Dec 27 14:50:31 CST 2020
     */
    public Integer getEndIndex() {
        return endIndex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ccks_entity.end_index
     *
     * @param endIndex the value for ccks_entity.end_index
     *
     * @mbg.generated Sun Dec 27 14:50:31 CST 2020
     */
    public void setEndIndex(Integer endIndex) {
        this.endIndex = endIndex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ccks_entity.text_id
     *
     * @return the value of ccks_entity.text_id
     *
     * @mbg.generated Sun Dec 27 14:50:31 CST 2020
     */
    public Long getTextId() {
        return textId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ccks_entity.text_id
     *
     * @param textId the value for ccks_entity.text_id
     *
     * @mbg.generated Sun Dec 27 14:50:31 CST 2020
     */
    public void setTextId(Long textId) {
        this.textId = textId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ccks_entity.commit_user_id
     *
     * @return the value of ccks_entity.commit_user_id
     *
     * @mbg.generated Sun Dec 27 14:50:31 CST 2020
     */
    public Long getCommitUserId() {
        return commitUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ccks_entity.commit_user_id
     *
     * @param commitUserId the value for ccks_entity.commit_user_id
     *
     * @mbg.generated Sun Dec 27 14:50:31 CST 2020
     */
    public void setCommitUserId(Long commitUserId) {
        this.commitUserId = commitUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ccks_entity
     *
     * @mbg.generated Sun Dec 27 14:50:31 CST 2020
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", entityId=").append(entityId);
        sb.append(", entityContent=").append(entityContent);
        sb.append(", startIndex=").append(startIndex);
        sb.append(", endIndex=").append(endIndex);
        sb.append(", textId=").append(textId);
        sb.append(", commitUserId=").append(commitUserId);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}