package com.yang.ccks2.mapper;

import com.yang.ccks2.model.CcksText;
import com.yang.ccks2.model.CcksTextExample;
import java.util.List;

import com.yang.ccks2.utils.CountResultMap;
import org.apache.ibatis.annotations.Param;

public interface CcksTextMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ccks_text
     *
     * @mbg.generated Sun Dec 27 14:50:31 CST 2020
     */
    long countByExample(CcksTextExample example);

    List<CountResultMap> countAllByTextName();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ccks_text
     *
     * @mbg.generated Sun Dec 27 14:50:31 CST 2020
     */
    int deleteByExample(CcksTextExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ccks_text
     *
     * @mbg.generated Sun Dec 27 14:50:31 CST 2020
     */
    int deleteByPrimaryKey(Long textId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ccks_text
     *
     * @mbg.generated Sun Dec 27 14:50:31 CST 2020
     */
    int insert(CcksText record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ccks_text
     *
     * @mbg.generated Sun Dec 27 14:50:31 CST 2020
     */
    int insertSelective(CcksText record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ccks_text
     *
     * @mbg.generated Sun Dec 27 14:50:31 CST 2020
     */
    List<CcksText> selectByExampleWithBLOBs(CcksTextExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ccks_text
     *
     * @mbg.generated Sun Dec 27 14:50:31 CST 2020
     */
    List<CcksText> selectByExample(CcksTextExample example);



    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ccks_text
     *
     * @mbg.generated Sun Dec 27 14:50:31 CST 2020
     */
    CcksText selectByPrimaryKey(Long textId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ccks_text
     *
     * @mbg.generated Sun Dec 27 14:50:31 CST 2020
     */
    int updateByExampleSelective(@Param("record") CcksText record, @Param("example") CcksTextExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ccks_text
     *
     * @mbg.generated Sun Dec 27 14:50:31 CST 2020
     */
    int updateByExampleWithBLOBs(@Param("record") CcksText record, @Param("example") CcksTextExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ccks_text
     *
     * @mbg.generated Sun Dec 27 14:50:31 CST 2020
     */
    int updateByExample(@Param("record") CcksText record, @Param("example") CcksTextExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ccks_text
     *
     * @mbg.generated Sun Dec 27 14:50:31 CST 2020
     */
    int updateByPrimaryKeySelective(CcksText record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ccks_text
     *
     * @mbg.generated Sun Dec 27 14:50:31 CST 2020
     */
    int updateByPrimaryKeyWithBLOBs(CcksText record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ccks_text
     *
     * @mbg.generated Sun Dec 27 14:50:31 CST 2020
     */
    int updateByPrimaryKey(CcksText record);
}
