package com.yang.ccks2.mapper;

import com.yang.ccks2.model.CcksUser;
import com.yang.ccks2.model.CcksUserExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface CcksUserMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ccks_user
     *
     * @mbg.generated Sun Dec 27 14:50:31 CST 2020
     */
    long countByExample(CcksUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ccks_user
     *
     * @mbg.generated Sun Dec 27 14:50:31 CST 2020
     */
    int deleteByExample(CcksUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ccks_user
     *
     * @mbg.generated Sun Dec 27 14:50:31 CST 2020
     */
    int deleteByPrimaryKey(Long userId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ccks_user
     *
     * @mbg.generated Sun Dec 27 14:50:31 CST 2020
     */
    int insert(CcksUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ccks_user
     *
     * @mbg.generated Sun Dec 27 14:50:31 CST 2020
     */
    int insertSelective(CcksUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ccks_user
     *
     * @mbg.generated Sun Dec 27 14:50:31 CST 2020
     */
    List<CcksUser> selectByExample(CcksUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ccks_user
     *
     * @mbg.generated Sun Dec 27 14:50:31 CST 2020
     */
    CcksUser selectByPrimaryKey(Long userId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ccks_user
     *
     * @mbg.generated Sun Dec 27 14:50:31 CST 2020
     */
    int updateByExampleSelective(@Param("record") CcksUser record, @Param("example") CcksUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ccks_user
     *
     * @mbg.generated Sun Dec 27 14:50:31 CST 2020
     */
    int updateByExample(@Param("record") CcksUser record, @Param("example") CcksUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ccks_user
     *
     * @mbg.generated Sun Dec 27 14:50:31 CST 2020
     */
    int updateByPrimaryKeySelective(CcksUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ccks_user
     *
     * @mbg.generated Sun Dec 27 14:50:31 CST 2020
     */
    int updateByPrimaryKey(CcksUser record);
}