package com.yang.ccks2.mapper;

import com.yang.ccks2.model.TextCount;
import com.yang.ccks2.model.TextCountExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TextCountMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table text_count
     *
     * @mbg.generated Sun Dec 27 14:50:31 CST 2020
     */
    long countByExample(TextCountExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table text_count
     *
     * @mbg.generated Sun Dec 27 14:50:31 CST 2020
     */
    int deleteByExample(TextCountExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table text_count
     *
     * @mbg.generated Sun Dec 27 14:50:31 CST 2020
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table text_count
     *
     * @mbg.generated Sun Dec 27 14:50:31 CST 2020
     */
    int insert(TextCount record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table text_count
     *
     * @mbg.generated Sun Dec 27 14:50:31 CST 2020
     */
    int insertSelective(TextCount record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table text_count
     *
     * @mbg.generated Sun Dec 27 14:50:31 CST 2020
     */
    List<TextCount> selectByExample(TextCountExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table text_count
     *
     * @mbg.generated Sun Dec 27 14:50:31 CST 2020
     */
    TextCount selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table text_count
     *
     * @mbg.generated Sun Dec 27 14:50:31 CST 2020
     */
    int updateByExampleSelective(@Param("record") TextCount record, @Param("example") TextCountExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table text_count
     *
     * @mbg.generated Sun Dec 27 14:50:31 CST 2020
     */
    int updateByExample(@Param("record") TextCount record, @Param("example") TextCountExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table text_count
     *
     * @mbg.generated Sun Dec 27 14:50:31 CST 2020
     */
    int updateByPrimaryKeySelective(TextCount record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table text_count
     *
     * @mbg.generated Sun Dec 27 14:50:31 CST 2020
     */
    int updateByPrimaryKey(TextCount record);
}